version: "3.9"

# Rodar com:
# docker compose -f infra/docker-compose.infra.yml -f infra/docker-compose.apps.yml -f infra/docker-compose.e2e.yml run --rm e2e

services:
  e2e:
    image: python:3.11-slim
    depends_on:
      - kafka
      - mongo
      - orchestrator
      - svc-inventory
      - svc-payment
      - svc-shipping
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e:ro   # ← se sua pasta e2e está na raiz do repo
    environment:
      - E2E_MODE=both
      - E2E_BROKERS=kafka:9092
      - E2E_MONGO_URL=mongodb://mongo:27017
      - E2E_MONGO_DB=orchestrator
    command: >
